version: '2'
services:
    cryptoinvest-app:
        image: cryptoinvest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cryptoinvest-mysql:3306/cryptoinvest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cryptoinvest-mysql:
        extends:
            file: mysql.yml
            service: cryptoinvest-mysql
